### ISSUE TITLE
deprecated --v2-config-only flag breaks Envoy on Windows

### ISSUE THREAD

**Issue by sesmith177** [cloudfoundry/executor#43]
When starting Envoy, we pass the command line argument `--v2-config-only`:

https://github.com/cloudfoundry/executor/blob/e98ca864b8413d6120ac9a74a79506aff9c27954/depot/transformer/transformer.go#L724

This breaks our Windows build since our fork has moved past this commit: https://github.com/envoyproxy/envoy/commit/0035f052617be2c641d8acd06a0331981d5da268 which removes the deprecated flag.

I think we can probably remove this flag, since the version of Envoy bundled in diego-release has the behavior enabled by this flag on by default

**Comment by emalm** [comment]
Thanks, @sesmith177, we'll take a look soon! /cc @sunjayBhatia @rosenhouse @ameowlia for their consideration too.

Best,
Eric

**Comment by rosenhouse** [comment]
Yeah, it was helpful for debugging back in the day.  We can remove, and should probably do the same in cloudfoundry/istio-release [here](https://github.com/cloudfoundry/istio-release/blob/65317f1ceff25cade41f0a91aaf616e88a92c6c8/jobs/envoy/templates/bpm.yml.erb#L8)

cc: @cloudfoundry/cf-networking @xanderstrike

**Comment by sunjayBhatia** [comment]
closing, as we resolved this issue
