### ISSUE TITLE
when an individual garden healthcheck hangs forever, the healthcheck runner deadlocks

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/executor#52]
This was recently observed in an environment where many Windows cells became unhealthy and stayed in that state until an operator intervened.

**Symptoms**
- cell is healthy
- we see the following log lines:
```
{"timestamp":"1579183191.195435047","source":"rep","message":"rep.garden-healthcheck.garden-health.healthcheck.starting","log_level":1,"data":{"session":"4.1.62"}}
...
{"timestamp":"1579183791.203859091","source":"rep","message":"rep.garden-healthcheck.set-state-unhealthy","log_level":4,"data":{"session":"4"}}
```
- this signifies that the garden healthcheck times out here: https://github.com/cloudfoundry/executor/blob/c59a0c25d8c563cbbe877e7e9304fc3f3e9679d6/gardenhealth/runner.go#L121-L123
- looking at the garden logs, we see:
```
{"timestamp":"1579183224.547698259","source":"guardian","message":"guardian.create.containerizer-create.runtime-create-failed","log_level":2,"data":{"error":"runc run: exit status 1: could not start command 'C:\\Windows\\Temp\\bin\\garden-init.exe' in container: executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.3"}}
{"timestamp":"1579183224.547698259","source":"guardian","message":"guardian.create.containerizer-create.finished","log_level":1,"data":{"handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.3"}}
{"timestamp":"1579183224.547698259","source":"guardian","message":"guardian.create.create-failed-cleaningup.start","log_level":1,"data":{"cause":"runc run: exit status 1: could not start command 'C:\\Windows\\Temp\\bin\\garden-init.exe' in container: executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.4"}}
{"timestamp":"1579183224.547698259","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.started","log_level":1,"data":{"cause":"runc run: exit status 1: could not start command 'C:\\Windows\\Temp\\bin\\garden-init.exe' in container: executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.4.1"}}
{"timestamp":"1579183224.547698259","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.started","log_level":1,"data":{"cause":"runc run: exit status 1: could not start command 'C:\\Windows\\Temp\\bin\\garden-init.exe' in container: executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.4.1.1"}}
{"timestamp":"1579183224.741655111","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.state","log_level":1,"data":{"cause":"runc run: exit status 1: could not start command 'C:\\Windows\\Temp\\bin\\garden-init.exe' in container: executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","handle":"executor-healthcheck-0a870967-7a67-4890-6360-e4bae865121b","session":"16877.4.1.1","state":{"Pid":0,"Status":"stopped"}}}
```
- notice the last few lines, we **never see the clean up after the failed create finish**
- the cell then continues to be reported in an unhealthy state indefinitely (until operator intervention to restart or recreate the cell)

**Cause**
- While the cause of why the create and subsequent cleanup are important to investigate and solve, we can point to logic in the garden healthchecker that exacerbates the issue when this is occurring
- if a healthcheck is running (forever) the timeout timer correctly goes off, sets the state of the cell to unhealthy, and tries to list/delete any existing healthcheck containers, however in the case that the healthcheck container creation is stuck, this does nothing to abort the running healthcheck: https://github.com/cloudfoundry/executor/blob/c59a0c25d8c563cbbe877e7e9304fc3f3e9679d6/gardenhealth/checker.go#L73-L87
- In order to reset the relevant timers in the healthchecker, the current healthcheck must finish: https://github.com/cloudfoundry/executor/blob/c59a0c25d8c563cbbe877e7e9304fc3f3e9679d6/gardenhealth/runner.go#L128-L140
- the only thing that sends on the channel to advance the state of this logic is finishing a healthcheck, otherwise we have a deadlock, the timeout timer is not even reset: https://github.com/cloudfoundry/executor/blob/c59a0c25d8c563cbbe877e7e9304fc3f3e9679d6/gardenhealth/runner.go#L171

**Proposed Improvements**
- log when a healthcheck times out for explicit confirmation in logs here: https://github.com/cloudfoundry/executor/blob/c59a0c25d8c563cbbe877e7e9304fc3f3e9679d6/gardenhealth/runner.go#L121-L123
- when a healthcheck times out, truly cancel it so the health checker can continue, this should report that the cell went unhealthy at that moment in time, but should continue to attempt further healthcheck probes so the cell can recover, unlike now where the cell is deadlocked and unhealthy forever, even if it can create and delete containers

**Risks**
- garden doesn't have any ability to abort a client connection if it is hanging, or time the connection out, so we may have to orphan connections and have a resource leak if this keeps happening
- we observed on Windows that while garden had not successfully created a container, the host compute service had, so there were further orphaned resources that we would leave behind when this occurs, and if it happens repeatedly we would be leaving these behind to pile up and potentially put the cell in a bad state

Would love to get the rest of the @cloudfoundry/cf-diego team's thoughts on this

cc @aemengo

**Comment by mariash** [comment]
Hi @sunjayBhatia we are closing issues in subrepos in favor of moving to managing Diego stories from github and getting better visibility by a team members for all issues in one place. I moved your issue to main diego-release: https://github.com/cloudfoundry/diego-release/issues/443
